services:
  glow-db:
    image: postgres:16-alpine
    container_name: glow-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Az01000001
      POSTGRES_DB: glow
    volumes:
      - glow_db_data:/var/lib/postgresql/data
    networks:
      - glow
    restart: unless-stopped

  glow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glow
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://postgres:Az01000001@glow-db:5432/glow?schema=public"
    depends_on:
      - glow-db
    networks:
      - glow
      - adam
    restart: unless-stopped

networks:
  glow:
    name: glow
  adam:
    external: true

volumes:
  glow_db_data:
